language: python

os: linux
services: xvfb

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# Cache can be cleared from the travis settings menu, see docs currently at
# https://docs.travis-ci.com/user/caching#Clearing-Caches
cache:
  - ccache

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - dvipng

env:
    global:
        # https://docs.travis-ci.com/user/environment-variables/        
        - NUMPY=1.14
        - ASTROPY=4.0
        - PYTHON=3.5
        - CONDA_DEPENDENCIES='scipy matplotlib ipython Cython setuptools_scm pip pytest'

        # PEP8 errors/warnings:
        # E101 - mix of tabs and spaces
        # W191 - use of tabs
        # W291 - trailing whitespace
        # W292 - no newline at end of file
        # W293 - trailing whitespace
        # W391 - blank line at end of file
        # E111 - 4 spaces per indentation level
        # E112 - 4 spaces per indentation level
        # E113 - 4 spaces per indentation level
        # E502 - the backslash is redundant between brackets
        # E722 - do not use bare except
        # E901 - SyntaxError or IndentationError
        # E902 - IOError
        - FLAKE8_OPT="--select=E101,W191,W291,W292,W293,W391,E111,E112,E113,E502,E722,E901,E902"

before_install:
  # Install the latest version of Miniconda
  - uname -a
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh
  - chmod +x miniconda3.sh
  - ./miniconda3.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - python --version

install:
    # You can add any CONDA channels you may need here. CONDA supports
    # both the commands add and append. The only difference is that 
    # the add command places the channel at the front of the priority 
    # list, while append does the opposite.
    - conda config --add channels conda-forge
    - conda config --add channels astropy
    - conda create --yes -n test python=$PYTHON
    - source activate test
    - conda install -y numpy=$NUMPY astropy=$ASTROPY
    - conda install -y $CONDA_DEPENDENCIES
    # - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - pip install pytest-pep8 
    - pip install pytest-cov
    - pip install coveralls
    - pip install sphinx-automodapi
    - pip install photutils
    - pip install sphinx-astropy
    - pip install graphviz
    - pip install -e .


jobs:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # Check for sphinx doc build warnings - we do this first because
        - python: 3.5
          script: python setup.py build_sphinx -w

        # Try older numpy versions
        - python: 3.6
          env: numpy=1.14
        - python: 3.6
          env: numpy=1.15
        - python: 3.7
          env: numpy=1.14
        - python: 3.7
          env: numpy=1.15
        - python: 3.7
          env: astropy=3.2.3 numpy=1.15
        - python: 3.8
          env: astropy=4.0 numpy=1.18
        

        # Do coverage tests
        - python: 3.7
          env: test --cov


        # Do a pep8 test
        - python: 3.7
          script: flake8 imexam --count $FLAKE8_OPT




    # As described above, using ci-helpers, you should be able to set up an
    # environment with dependencies installed using conda and pip, but in some
    # cases this may not provide enough flexibility in how to install a
    # specific dependency (and it will not be able to install non-Python
    # dependencies). Therefore, you can also include commands below (as
    # well as at the start of the install section or in the before_install
    # section if they are needed before setting up conda) to install any
    # other dependencies.

script: python setup.py test


after_success:
    - coveralls --rcfile='imexam/tests/coveragerc'
